# image: cypress/base:10
image: node:latest

stages:
    - build
    - test
    - merge

cache:
    paths:
        - .eaasi-web-api/node_modules/
        - .eaasi-front-end/node_modules/

# Build Jobs
install_vue_npm_packages:
    stage: build
    script:
        - cd ./eaasi-front-end
        - npm install
        - npm run build
    only:
        - merge_requests

install_web_api_npm_packages:
    stage: build
    script:
        - cd ./eaasi-web-api
        - npm install
        - npm install -g babel-cli
        - npm run build
    only:
        - merge_requests

# Test Runner Jobs

run_api_unit_tests:
    stage: test
    script:
        - cd ./eaasi-web-api
        - npm install -g jest
        - npm install
        - jest --verbose --detectOpenHandles --logHeapUsage --coverage
    only:
        - merge_requests

run_vue_unit_tests:
    stage: test
    script:
        - cd ./eaasi-front-end
        - npm install -g jest
        - npm install
        - npm run test:unit
    only:
        - merge_requests
