stages:
    - build
    - deploy

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

build:
    stage: build
    script:
        - docker-compose build
    tags:
        - docker-test

deploy-containers:
    stage: deploy
    script:
        - export DOCKER_HOST=ssh://portalmedia@66.222.124.3
        - cd eaasi/eaasi-client-dev
        - docker-compose down -v
        - docker-compose up -d
        - unset DOCKER_HOST
    tags:
        - docker-test