# image: cypress/base:10
image: node:lts

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - test

cache:
    paths:
        - .eaasi-web-api/node_modules/
        - .eaasi-front-end/node_modules/

build:front-end:
    stage: build
    script:
        - cd ./eaasi-front-end
        - npm install
        - npm run build
    only:
        - merge_requests

build:api:
    stage: build
    script:
        - cd ./eaasi-web-api
        - npm install
        - npm install -g babel-cli
        - npm run build
    only:
        - merge_requests

test:front-end:
    stage: test
    dependencies:
        - build:front-end
    script:
        - cd ./eaasi-front-end
        - npm install -g jest
        - npm install
        - npm run test:unit
    only:
        - merge_requests

test:api:
    stage: test
    dependencies:
        - build:api
    script:
        - cd ./eaasi-web-api
        - npm install -g jest
        - npm install
        - jest --verbose --detectOpenHandles --logHeapUsage --coverage
    only:
        - merge_requests
