stages:
    - deploy

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - apk add --no-cache py-pip
    - pip install docker-compose


deploy-containers:
    stage: deploy
    script:
        - export DOCKER_HOST=ssh://portalmedia@66.222.124.3/eaasi/eaasi-client-dev
        - git checkout master
        - git pull --recurse-submodules
        - docker-compose down -v
        - docker-compose build && docker-compose up -d
        - unset DOCKER_HOST