version: "3"

services:
  # PostgresQL Database
  eaasi-database:
    image: eaasi-database
    build:
        context: ./eaasi-client-database
    env_file:
        - ./eaasi-client-database/vars.env
    ports:
        - 5432:5432
    volumes:
        - eaasi_db:/var/lib/postgresql/data

  # Vue.js Front End SPA
  eaasi-client:
    image: eaasi-client
    build:
        context: ./eaasi-front-end
    ports:
        - 8080:80

volumes:
    # Database Data
    eaasi_db:
