version: "3.7"

networks:
  eaasi:
    name: eaasi

services:
  # Nginx Reverse Proxy
  eaasi-nginx:
    image: nginx:stable-alpine
    container_name: eaasi-nginx
    init: true
    depends_on:
    - eaasi-front-end
    - eaasi-web-api
    volumes:
    - ./eaasi-nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./eaasi-nginx/cache:/etc/nginx/cache
    - ./eaasi-nginx/certs:/etc/nginx/certs
    networks:
    - eaasi
    ports:
    - 80:80
    restart: always

  # Vue.js Front End SPA
  eaasi-front-end:
    image: eaasi-front-end
    container_name: eaasi-front-end
    init: true
    build:
      context: .
    networks:
    - eaasi
    ports:
    - 8080:80
    restart: on-failure

  # Express Web API
  eaasi-web-api:
    image: eaasi-web-api
    container_name: eaasi-web-api
    init: true
    build:
      context: ./eaasi-web-api
    env_file:
    - ./eaasi-web-api/.env
    volumes:
    - ./eaasi-web-api/certs:/app/certs
    networks:
    - eaasi
    external_links:
    - eaasi-nginx:eaasi.portalmedia.com
    ports:
    - 8081:8081
    restart: on-failure
