version: "3"

services:
  # PostgresQL Database
  eaasi-database:
    image: eaasi-database
    build:
        context: ./eaasi-client-database
    env_file:
        - ./eaasi-client-database/vars.env
    ports:
        - 5432:5432
    volumes:
        - eaasi_db:/var/lib/postgresql/data

  # Vue.js Front End SPA
  eaasi-client:
    image: eaasi-client
    build:
        context: ./eaasi-front-end
    ports:
        - 8080:80

  # CAS Development Server
  eaasi-cas:
    image: eaasi-cas
    build:
        context: ./cas-test-server
    ports:
        - "8443:8443"

  # Express Web API
  eaasi-web-api:
    image: eaasi-web-api
    build:
        context: ./eaasi-client-web-api
    depends_on:
        - eaasi-database
        - eaasi-cas
    env_file:
          # do not check into version control
        - ./eaasi-client-web-api/env/prod.env
    ports:
        - 8081:8081
    command: bash -c "./wait-for-it.sh eaasi-database:5432 -- \
                      npx sequelize-cli db:migrate \
                      && npx sequelize-cli db:seed:all \
                      && npm run prod"

volumes:
    # Database Data
    eaasi_db:
