FROM postgres:11.3-alpine

# Copy entrypoint scripts to create test user and test database

COPY ./create_test_user.sh   /docker-entrypoint-initdb.d/01-create_user.sh
COPY ./create_test_db.sh   /docker-entrypoint-initdb.d/02-create_db.sh
