module.exports = {
	moduleFileExtensions: ['js', 'json', 'ts', 'd.ts'],
	transformIgnorePatterns: ['/node_modules/'],
	moduleNameMapper: {
		'^@/(.*)$': '<rootDir>/src/$1',
	},
	testURL: 'http://localhost/',
	testMatch: ['**/test/unit/**/*.(js|ts)'],
	collectCoverage: true,
	cacheDirectory: "../.jest",
	testResultsProcessor: "jest-sonar-reporter",
	coveragePathIgnorePatterns: [
		'/node_modules/',
		'/src/data_access/migrations/',
		'/src/data_access/seeders/',
		'/src/data_access/models/audio-device/',
		'/src/data_access/models/base/',
		'/src/data_access/models/computing/',
		'/src/data_access/models/configured/',
		'/src/data_access/models/content/',
		'/src/data_access/models/display/',
		'/src/data_access/models/file/',
		'/src/data_access/models/geo/',
		'/src/data_access/models/gpu/',
		'/src/data_access/models/keyboard/',
		'/src/data_access/models/machine/',
		'/src/data_access/models/network/',
		'/src/data_access/models/os/',
		'/src/data_access/models/pointer/',
		'/src/data_access/models/processor/',
		'/src/data_access/models/software/',
		'/src/data_access/models/storage/',
		'/src/data_access/models/system/',
		'/src/data_access/models/timezone/',
	]
};
