image: cypress/base:10

stages:
    - build
    - test

cache:
    paths:
        - ./node_modules/

install_npm_packages:
    stage: build
    script:
        - npm install

run_tests:
    stage: test
    script:
        - npm run test:styleguide:ci

