image: node:latest

stages:
    - build
    - test

cache:
    paths:
        - ./node_modules/

install_npm_packages:
    stage: build
    script:
        - npm install

run_tests:
    stage: test
    script:
        - npm install -g jest
        - jest --verbose --detectOpenHandles --logHeapUsage --coverage

