.testjob:
  image: node:lts-alpine
  stage: test
  variables:
    npm_cache_dir: ".npm"
    jest_cache_dir: ".jest"
  cache:
    key: "cache-${CI_JOB_NAME}"
    paths:
    - "${npm_cache_dir}"
    - "${jest_cache_dir}"
  script:
  - apk add git
  - node --version
  - cd "${service}"
  - npm ci --cache "../${npm_cache_dir}"
  - npm run "test:unit:coverage"

front-end-tests:
  extends: ".testjob"
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    service: "eaasi-front-end"

web-api-tests:
  extends: ".testjob"
  variables:
    service: "eaasi-web-api"
