.testjob:
  image: node:lts-alpine
  stage: test
  variables:
    cachedir: ".npm"
  cache:
    key: "cache-${CI_JOB_NAME}"
    paths:
    - "${cachedir}"
  script:
  - cd "${service}"
  - npm ci --cache "../${cachedir}"
  - NODE_OPTIONS=--max-old-space-size=8000 npm run "test:unit"

front-end-tests:
  extends: ".testjob"
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    service: "eaasi-front-end"

web-api-tests:
  extends: ".testjob"
  variables:
    service: "eaasi-web-api"
