name: Teleport
on:
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    strategy:
      matrix:
        service: [ "eaasi-front-end", "eaasi-web-api" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and run tests
        env:
          GIT_SUBMODULE_STRATEGY: 'recursive'
          npm_cache_dir: '.npm'
          jest_cache_dir: '.jest'
          SERVICE: ${{ matrix.service }}
        run: |
          apk add git || true
          node --version
          cd "$SERVICE"
          npm ci --cache "../$npm_cache_dir"
          npm run "test:unit:coverage"
